package io.github.khomy86.lgp.recognition

import android.content.Context
import org.json.JSONObject

data class Gesture(
    val id: String,
    val name: String,
    val meaning: String,
    val handShape: String,
)

/** The gestures the model knows and how its output is smoothed. Generated by ml/export.py. */
data class GestureCatalog(
    val gestures: List<Gesture>,
    val smoothingWindow: Int,
    val minConfidence: Float,
) {
    companion object {
        private const val ASSET = "gestures.json"

        fun load(context: Context): GestureCatalog {
            val json = JSONObject(context.assets.open(ASSET).bufferedReader().use { it.readText() })
            val gestures = json.getJSONArray("gestures").let { array ->
                List(array.length()) { i ->
                    val item = array.getJSONObject(i)
                    Gesture(
                        id = item.getString("id"),
                        name = item.getString("name"),
                        meaning = item.getString("meaning"),
                        handShape = item.getString("handShape"),
                    )
                }
            }
            return GestureCatalog(
                gestures = gestures,
                smoothingWindow = json.getInt("smoothingWindow"),
                minConfidence = json.getDouble("minConfidence").toFloat(),
            )
        }
    }
}
